import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import register from './register/page'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session=await getServerSession(authOptions)
  if(session){
    console.log(session)
  }
  
  return (
    <html lang="en">
      <Head>
          <title>쇼핑몰</title>
          <meta name="description" content="쇼핑몰 nextjs로 만들기" />
          <meta name="keyword" content="로그인 만들기, 회원가입 만들기, db생성하기" />
      </Head>
      <body className={inter.className}>

        <div className="top-logo">
          <Link href="/"><img src="/img/logo1.png" alt="logo" /></Link>
        </div>
        <div className='g-menu'>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li>{session ? <LogoutBtn></LogoutBtn> : <LoginBtn></LoginBtn>}</li>
            <li><Link href="register">Join</Link></li>
            <li><Link href="cart">Cart</Link></li>
            <li><Link href="notice">Notice</Link></li>
          </ul>/
        </div>
        <nav className="menu">
          <ul>
            <li><Link href="/best100">BEST100</Link></li>
            <li><Link href="/new">NEW</Link></li>
            <li><Link href="/stay">STAY</Link></li>
            <li><Link href="/travel">TRAVEL</Link></li>
            <li><Link href="/activity">ACTIVITY</Link></li>
          </ul>
        </nav>
        {children}
        <div className="footer">
          <div className="footer-inner">
            <ul>
              <li>
                <h4>NOTIFICATION</h4>
                <ul>
                  <li><Link href="/notification">회사소개</Link></li>
                  <li><Link href="/">이용약관</Link></li>
                  <li><Link href="/">이용안내</Link></li>
                  <li><Link href="/">개인정보 취급방침</Link></li>
                  <li><Link href="/">협찬/제휴문의</Link></li>
                </ul>
              </li>
              <li>
                <h4>COMPANY INFOMATION</h4>
                <ul>
                  <li><Link href="/">Company.(주)하루컴퍼니</Link></li>
                  <li><Link href="/">서울 서초구 일성빌딩 9층 905호</Link></li>
                  <li><Link href="/">Owner.박하루방</Link></li>
                  <li><Link href="/">Bnsiness License.204-12-123456</Link></li>
                  <li><Link href="/">Copyright &copy cho line. All Rights Reserved.</Link></li>
                </ul>
              </li>
              <li>
                <h4>BANK ACCOUNT</h4>
                <p>무통장 입금안내</p>
                <ul>
                  <li><Link href="/">국민 654321-04-51352</Link></li>
                  <li><Link href="/">농협 123456-4513</Link></li>
                  <li><Link href="/">신한 11-513-548</Link></li>
                  <li><Link href="/">우리 2158-413-542</Link></li>
                  <li><Link href="/">기업 110-125842-512115</Link></li>
                </ul>
              </li>
              <li>
                <h4>CS CENTER</h4>
                <ul>
                  <li><Link href="/">Weekday AM 10:00 - PM 4:00</Link></li>
                  <li><Link href="/">Lunch PM 12:00 - PM 13:00</Link></li>
                  <li><Link href="/">SAT/SUN/HOLIDAY.OFF</Link></li>
                  <li><span>전화량이 많아 게시판을 이용해주시면 <br /> 감사하겠습니다.</span></li>
                </ul>
                <p>1544-8282</p>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  )
}
